"""Added created_at and updated_at columns.

Revision ID: 662137705dd4
Revises: 0c52722fdd1a
Create Date: 2021-12-23 19:52:32.616131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '662137705dd4'
down_revision = '0c52722fdd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('employees', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('employers', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('employers', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('employers', 'updated_at')
    op.drop_column('employers', 'created_at')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    # ### end Alembic commands ###
